// This file defines the paramters that the procedural generation system 
// will use to generate a dungeon. These parameters are generated by the 
// PcgPolicyRunner class, which takes the output of the onnx model and 
// converts it into a set of parameters that can be used to generate a dungeon.

using System;

[Serializable]
public class PcgGenerationParameters
{
    public int RoomCount;

    public int AreaWidth;
    public int AreaHeight;

    public int MinRoomWidth;
    public int MaxRoomWidth;

    public int MinRoomHeight;
    public int MaxRoomHeight;

    // public int AdjacentRoomConnections;

    // public float EnemyDensity;
    // public float ContentDensity;

    public int Seed;
}